--[[

	This file is part of 'Masque', an add-on for World of Warcraft. For bug reports,
	suggestions and license information, please visit https://github.com/SFX-WoW/Masque.

	* File...: Skins\Modern_Enhanced.lua
	* Author.: StormFX, Blizzard Entertainment

	"Modern Enhanced" Skin

]]

local _, Core = ...

----------------------------------------
-- Internal
---

-- @ Locales\enUS
local L = Core.Locale

-- @ Skins\Skins
local Hidden = Core._Hidden

----------------------------------------
-- Modern Enhanced
---

Core.AddSkin("Modern Enhanced", {
	-- API_VERSION = Template.API_VERSION,
	Shape = "Modern",
	Template = "Blizzard Modern",

	-- Info
	Authors = {"StormFX", "|cff0099ffBlizzard Entertainment|r"},
	Description = L["An enhanced version of the modern button style."],
	Discord = Core.Discord,
	-- Version = Template.Version,
	Websites = Core.Websites,

	-- Skin
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	Icon = {
		-- TexCoords = {0, 1, 0, 1},
		Width = 36,
		Height = 36,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		UseMask = true,
		Aura = {
			-- TexCoords = {0, 1, 0, 1},
			Width = 36,
			Height = 36,
			Point = "TOP",
			RelPoint = "TOP",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			UseMask = true,
		},
		BagSlot = {
			-- TexCoords = {0, 1, 0, 1},
			Width = 36,
			Height = 36,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			UseMask = true,
		},
		Item = {
			-- TexCoords = {0, 1, 0, 1},
			Width = 36,
			Height = 36,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
		},
	},
	-- Shadow = Template.Shadow,
	Normal = {
		Atlas = "UI-HUD-ActionBar-IconFrame",
		-- EmptyAtlas = "UI-HUD-ActionBar-IconFrame",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 0},
		-- EmptyColor = {1, 1, 1, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 37,
		Height = 36,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		OffsetX = 1,
		OffsetY = -0.5,
		-- SetAllPoints = nil,
		-- UseStates = true,
		Backpack = {
			Atlas = "Bag-Main",
			-- EmptyAtlas = "Bag-Main",
			-- UseAtlasSize = false,
			-- Color = {1, 1, 1, 1},
			-- EmptyColor = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 36,
			Height = 36,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			UseStates = true,
		},
		BagSlot = {
			Atlas = "Bag-Border",
			-- EmptyAtlas = "Bag-Border-Empty",
			-- UseAtlasSize = false,
			-- Color = {1, 1, 1, 1},
			-- EmptyColor = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			-- Width = 36,
			-- Height = 36,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			SetAllPoints = true,
			UseStates = true,
		},
		Item = {
			Texture = [[Interface\Buttons\UI-Quickslot2]],
			-- EmptyTexture = "Interface\\Buttons\\UI-Quickslot2",
			-- TexCoords = {0, 1, 0, 1},
			-- EmptyCoords = {0, 1, 0, 1},
			-- Color = {1, 1, 1, 1},
			-- EmptyColor = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 62,
			Height = 62,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			OffsetX = 0.5,
			OffsetY = -0.5,
			-- SetAllPoints = nil,
			UseStates = true,
		},
		ReagentBag = {
			Atlas = "Bag-Reagent-Border",
			-- EmptyAtlas = "Bag-Reagent-Border-Empty",
			-- UseAtlasSize = false,
			-- Color = {1, 1, 1, 1},
			-- EmptyColor = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			-- Width = 36,
			-- Height = 36,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			SetAllPoints = true,
			UseStates = true,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	Border = {
		Atlas = "UI-HUD-ActionBar-IconFrame-Border",
		-- UseAtlasSize = false, -- true
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 35,
		Height = 34,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		OffsetX = 0.5,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		Debuff = {
			Texture = [[Interface\Buttons\UI-Debuff-Overlays]],
			TexCoords = {0.296875, 0.5703125, 0, 0.515625},
			-- Color = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "OVERLAY",
			-- DrawLevel = 0,
			Width = 33,
			Height = 32,
			Anchor = "Icon",
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			OffsetY = -0.5,
			-- SetAllPoints = nil,
		},
		Enchant = {
			Texture = [[Interface\Buttons\UI-TempEnchant-Border]],
			-- TexCoords = {0, 1, 0, 1},
			-- Color = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "OVERLAY",
			-- DrawLevel = 0,
			Width = 38,
			Height = 38,
			Anchor = "Icon",
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
		},
		Item = {
			Texture = [[Interface\Common\WhiteIconFrame]],
			-- TexCoords = {0, 1, 0, 1},
			-- Color = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "OVERLAY",
			-- DrawLevel = 0,
			Width = 36,
			Height = 36,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
		},
	},
	DebuffBorder = {
		Texture = [[Interface\Buttons\UI-Debuff-Overlays]],
		TexCoords = {0.296875, 0.5703125, 0, 0.515625},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 33,
		Height = 32,
		Anchor = "Icon",
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		OffsetY = -0.5,
		-- SetAllPoints = nil,
	},
	EnchantBorder = "Border",
	-- IconBorder = Template.IconBorder,
	Gloss = {
		Texture = [[Interface\AddOns\Masque\Textures\Modern\Gloss]],
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 1, 1, 0.8},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 52,
		Height = 52,
		-- Anchor = "Icon",
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		Backpack = Hidden,
		BagSlot = Hidden,
		Item = Hidden,
	},
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	Highlight = {
		Atlas = "UI-HUD-ActionBar-IconFrame-Mouseover",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "ADD",
		-- DrawLayer = "HIGHLIGHT",
		-- DrawLevel = 0,
		Width = 35,
		Height = 34,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		OffsetX = 0.5,
		OffsetY = -0.5,
		-- SetAllPoints = nil,
		-- UseColor = nil,
		Backpack = {
			Atlas = "Bag-Main-Highlight",
			-- UseAtlasSize = false,
			Color = {1, 1, 1, 0.4},
			-- BlendMode = "ADD",
			-- DrawLayer = "HIGHLIGHT",
			-- DrawLevel = 0,
			Width = 36,
			Height = 36,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			-- UseColor = nil,
		},
		BagSlot = {
			Atlas = "Bag-Border-Highlight",
			-- UseAtlasSize = false,
			Color = {1, 1, 1, 0.4},
			-- BlendMode = "ADD",
			-- DrawLayer = "HIGHLIGHT",
			-- DrawLevel = 0,
			Width = 36,
			Height = 36,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			-- UseColor = nil,
		},
		Item = {
			Texture = [[Interface\Buttons\ButtonHilight-Square]],
			-- TexCoords = {0, 1, 0, 1},
			-- Color = {1, 1, 1, 1},
			-- BlendMode = "ADD",
			-- DrawLayer = "HIGHLIGHT",
			-- DrawLevel = 0,
			Width = 37,
			Height = 37,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			-- UseColor = nil,
		},
	},
	-- [ TextOverlayContainer ]
	-- HotKey = Template.HotKey,
	Count = {
		-- JustifyH = "RIGHT",
		-- JustifyV = "BOTTOM",
		-- DrawLayer = "OVERLAY",
		-- Width = 0,
		-- Height = 0,
		-- Anchor = "Icon",
		-- Point = "BOTTOMRIGHT",
		-- RelPoint = "BOTTOMRIGHT",
		OffsetX = -3,
		OffsetY = 3,
	},
	-- [ AutoCastShine (Classic) ]
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- [ AutoCastOverlay (Retail) ]
	-- AutoCast_Frame = Template.AutoCast_Frame,
	AutoCast_Mask = {
		-- Atlas = "UI-HUD-ActionBar-PetAutoCast-Mask",
		-- UseAtlasSize = false,
		Texture = [[Interface\AddOns\Masque\Textures\Modern\AutoCast-Mask]],
		-- TexCoords = {0, 1, 0, 1},
		Width = 30,
		Height = 30,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	-- AutoCast_Shine = Template.AutoCast_Shine,
	AutoCast_Corners = {
		Atlas = "UI-HUD-ActionBar-PetAutoCast-Corners",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 36,
		Height = 36,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = true,
	},
	-- [ Cooldowns ]
	Cooldown = {
		Texture = [[Interface\AddOns\Masque\Textures\Modern\Mask]],
		EdgeTexture = [[Interface\AddOns\Masque\Textures\Modern\Edge]],
		PulseTexture = [[Interface\Cooldown\star4]],
		Color = {0, 0, 0, 0.8},
		Width = 31,
		Height = 31,
		Anchor = "Icon",
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	ChargeCooldown = "Cooldown",
	-- [ SpellAlerts ]
	SpellAlert = {
		Height = 38,
		Width = 38,
		AltGlow = {
			Height = 45,
			Width = 45,
		},
		Classic = {
			Height = 30,
			Width = 30,
		},
		Modern = {
			Height = 32,
			Width = 32,
		},
		["Modern-Lite"] = {
			Height = 32,
			Width = 32,
		},
	},
	AssistedCombatHighlight = {
		Width = 45,
		Height = 45,
	},
}, true)
